# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - bioc-release
cache: packages
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libudunits2-dev
r_packages:
  - covr
warnings_are_errors: false
after_success:
  - Rscript -e 'library(covr); codecov()'
