# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
sudo: false
cache: packages
r_packages:
  - covr
warnings_are_errors: false
bioc_required: true
bioc_use_devel: true
after_success:
  - Rscript -e 'library(covr); codecov()'
